name = "freigen"
version = "0.1.0"
defaultTargets = ["freigen"]

[[lean_lib]]
name = "Freigen"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_exe]]
name = "freigen"
root = "Main"
