import ZkLean.Basic

/-!
# A PHOAS AST for free-monadic programs, with denotation and a reflecting elaborator

A sketch for *poking* at reflecting a real Lean term that builds a `Free F`
computation into an explicit syntax tree (`reflect%`), denoting that tree back into
`Free F` (`denoteP`), and handing back a *proof* that the round-trip is faithful.

We use **PHOAS** (Parametric Higher-Order Abstract Syntax): object-language
binders are Lean binders over an abstract variable representation `V : Type → Type`.
No de Bruijn indices, no capture — we reuse Lean's binders.

## One signature, two worlds

The crux is the effect signature.  An effect has two very different kinds of hole:
its **inputs** (data fed *in* — these should be object *terms*, hence may be
variables or anything computable) and its **result** (bound *out* in the
continuation — a PHOAS binder).  So we describe an effect once, by a tiny GADT
indexed by *(input type, result type)*:

```
Op : Type → Type → Type        -- `Op I R` : an operation taking an `I`, returning an `R`
```

From this single source we *derive* the functor the freer monad `Free` needs:

```
Effect Op R := Σ I, Op I R × I  -- an op returning `R`, packaged with its input value
```

so the runtime monad is the ordinary `Free (Effect Op)` from `ZkLean.Basic`, while
the syntax tree's `op` node uses the very same `Op`, with the input as a term
`Tm V I` and the result as a binder `V R`.  `denoteP` bridges the two by evaluating
the input term and packing it into `Effect.mk`.

The AST is split into two families, which keeps every universe at the bottom:

* `Tm  V τ`    — the pure λ-calculus fragment (`var` / `lit` / `lam` / `app` / `letE`).
* `Prog Op V α` — the free-monadic fragment (`ret` / `bind` / `op`).
-/

namespace ZkFree

open Lean Lean.Meta Lean.Elab Lean.Elab.Term

/-! ## The effect signature and its derived functor -/

/-- The freer-monad functor generated by an operation signature `Op`: one effect
    layer returning `R` is some operation `Op I R` packaged with its input `I`. -/
structure Effect (Op : Type → Type → Type) (R : Type) : Type 1 where
  {I : Type}
  op  : Op I R
  inp : I

/-! ## The AST -/

/-- Pure PHOAS λ-terms. -/
inductive Tm (V : Type → Type) : Type → Type 1
  /-- A bound object variable. -/
  | var {α : Type} : V α → Tm V α
  /-- A `Nat` literal lifted into the object language. -/
  | lit : Nat → Tm V Nat
  /-- Object-language λ. -/
  | lam {α β : Type} : (V α → Tm V β) → Tm V (α → β)
  /-- Object-language application (a "call"). -/
  | app {α β : Type} : Tm V (α → β) → Tm V α → Tm V β
  /-- A normal (non-monadic) `let`. -/
  | letE {α β : Type} : Tm V α → (V α → Tm V β) → Tm V β

/-- Free-monadic PHOAS programs over an operation signature `Op`. -/
inductive Prog (Op : Type → Type → Type) (V : Type → Type) : Type → Type 1
  /-- Monadic `pure` of a pure term. -/
  | ret {α : Type} : Tm V α → Prog Op V α
  /-- Monadic `bind` (`>>=`); the continuation binds the *value* of type `α`. -/
  | bind {α β : Type} : Prog Op V α → (V α → Prog Op V β) → Prog Op V β
  /-- Perform operation `Op I R`: its **input** is an object term `Tm V I` (so it
      may be a variable!), and its **result** `R` is bound in the continuation. -/
  | op {α I R : Type} : Op I R → Tm V I → (V R → Prog Op V α) → Prog Op V α

/-- A *closed* program: parametric in the variable representation. -/
def Closed (Op : Type → Type → Type) (α : Type) : Type 1 := ∀ V, Prog Op V α

/-! ## Denotation (the identity interpreter, `V := Id`) -/

/-- Denote a pure term to its Lean value. -/
def denoteT {τ : Type} : Tm Id τ → τ
  | .var v    => v
  | .lit a    => a
  | .lam f    => fun x => denoteT (f x)
  | .app f a  => (denoteT f) (denoteT a)
  | .letE v k => denoteT (k (denoteT v))

/-- Denote a program to a real `Free (Effect Op)` computation: the `op` node's
    input term is evaluated and packed into the derived `Effect` functor. -/
def denoteP {Op : Type → Type → Type} {α : Type} : Prog Op Id α → Free (Effect Op) α
  | .ret t     => Free.Pure (denoteT t)
  | .bind p k  => freeBind (denoteP p) (fun x => denoteP (k x))
  | .op o i k  => Free.Impure ⟨o, denoteT i⟩ (fun r => denoteP (k r))

/-! ## The `reflect%` elaborator

`reflect% e` takes a real Lean term `e : A₁ → … → Aₙ → Free (Effect Op) τ` (a
function returning a free-monadic value; `n = 0` is allowed) and produces

```
reflect% e : { g : A₁ → … → Aₙ → Prog Op Id τ // ∀ a…, denoteP (g a…) = e a… }
```

The AST is built so that `denoteP` of it is *definitionally* the original
computation, so the soundness proof is just `rfl`.
-/

/-- The identity-functor `V := Id` at `Type 0`, the variable representation that
    `reflect%` targets. -/
private def idExpr : Expr := .const ``Id [.zero]

/-- A reflection environment: the abstract variable representation `V` we build
    against, plus a substitution from each continuation-bound host placeholder to
    the object variable (`vx : V R`) that should replace it. -/
private structure Env where
  V : Expr
  subst : List (FVarId × Expr)

private def Env.mkVar (env : Env) (vx : Expr) : MetaM Expr :=
  mkAppOptM ``Tm.var #[env.V, none, vx]

private def Env.mkLit (env : Env) (a : Expr) : MetaM Expr :=
  mkAppOptM ``Tm.lit #[env.V, a]

/-- Reflect a pure value Expr into a `Tm V _`.  A continuation-bound variable
    becomes `var`; a host `Nat` (a literal or a function argument) becomes `lit`;
    a *computation* that mentions a bound variable is rejected — it cannot live in
    a `∀ V` program. -/
private def Env.reflectLeaf (env : Env) (a : Expr) : MetaM Expr := do
  if let .fvar fid := a then
    match env.subst.lookup fid with
    | some vx => env.mkVar vx
    | none =>
      if ← isDefEq (← inferType a) (.const ``Nat []) then env.mkLit a
      else throwError "reflect%: free variable is not a `Nat`{indentExpr a}"
  else if a.hasAnyFVar fun fid => (env.subst.lookup fid).isSome then
    throwError "reflect%: cannot reflect a computation on a bound variable into a \
                `∀ V` program (the object language has no operations on `V`-values); \
                thread the variable instead, or reflect at `V := Id`.{indentExpr a}"
  else if ← isDefEq (← inferType a) (.const ``Nat []) then env.mkLit a
  else throwError "reflect%: values must be a bound variable or a `Nat`{indentExpr a}"

private def Env.mkRet (env : Env) (Op a : Expr) : MetaM Expr := do
  mkAppOptM ``Prog.ret #[Op, env.V, none, ← env.reflectLeaf a]

private def Env.mkBind (env : Env) (Op p k : Expr) : MetaM Expr :=
  mkAppOptM ``Prog.bind #[Op, env.V, none, none, p, k]

private def Env.mkOp (env : Env) (Op o inp k : Expr) : MetaM Expr :=
  mkAppOptM ``Prog.op #[Op, env.V, none, none, none, o, inp, k]

mutual
  /-- Reflect a host `Free (Effect Op) _` expression into a `Prog Op V _`. -/
  private partial def walkProg (env : Env) (Op e : Expr) : MetaM Expr := do
    let e := e.consumeMData.headBeta
    -- zeta-reduce `let`/`have` introduced by `do`-elaboration
    if let .letE _ _ v b _ := e then
      return ← walkProg env Op (b.instantiate1 v)
    match_expr e with
    | Free.Pure _ _ a         => env.mkRet Op a
    | Pure.pure _ _ _ a       => env.mkRet Op a
    | Bind.bind _ _ _ _ x f   => env.mkBind Op (← walkProg env Op x) (← walkCont env Op f)
    | freeBind _ _ _ x f      => env.mkBind Op (← walkProg env Op x) (← walkCont env Op f)
    | Free.Impure _ _ _ eff k =>
      -- `eff : Effect Op R` is `Effect.mk o inp`; lift the input to a term
      match_expr eff with
      | Effect.mk _ _ _ o inp => env.mkOp Op o (← env.reflectLeaf inp) (← walkCont env Op k)
      | _ => throwError "reflect%: effect is not an `Effect.mk`{indentExpr eff}"
    | _ =>
      -- a smart constructor / user definition: unfold its head and retry
      match ← unfoldDefinition? e with
      | some e' => walkProg env Op e'
      | none    => throwError "reflect%: don't know how to reflect computation{indentExpr e}"

  /-- Reflect a host continuation `f : X → Free (Effect Op) _` into the object
      continuation `fun (vx : V X) => …`.  We introduce two locals: the object
      variable `vx : V X` that the result binds, and a host placeholder `hx : X`
      to symbolically evaluate `f`'s body — occurrences of `hx` are rewritten to
      `var vx` via the substitution. -/
  private partial def walkCont (env : Env) (Op f : Expr) : MetaM Expr := do
    let fty ← whnf (← inferType f)
    let .forallE _ X _ _ := fty
      | throwError "reflect%: expected a continuation function, got{indentExpr fty}"
    withLocalDeclD `v (.app env.V X) fun vx =>
    withLocalDeclD `h X fun hx => do
      let env' := { env with subst := (hx.fvarId!, vx) :: env.subst }
      let body ← walkProg env' Op (f.beta #[hx])
      mkLambdaFVars #[vx] body
end

elab "reflect% " t:term : term => do
  let e ← elabTerm t none
  synthesizeSyntheticMVarsNoPostponing
  let e ← instantiateMVars e
  -- Telescope the *type* (so this also works when `e` is a bare constant, not a
  -- literal `fun`), then apply `e` to the introduced arguments.
  forallTelescope (← inferType e) fun args codom => do
    let bty ← whnf codom
    let_expr Free F τ := bty
      | throwError "reflect%: the body must have type `Free F τ`, got{indentExpr bty}"
    let_expr Effect Op := F
      | throwError "reflect%: the functor must be `Effect Op`, got{indentExpr F}"
    -- Build the program against an abstract `V : Type → Type`.
    let tyTy := mkSort (.succ .zero)
    withLocalDeclD `V (← mkArrow tyTy tyTy) fun V => do
      let prog ← walkProg { V := V, subst := [] } Op (e.beta args)
      -- g := fun V args => prog   (so `g.1` is `Closed Op τ` when there are no args)
      let g ← mkLambdaFVars (#[V] ++ args) prog
      let gTy ← inferType g
      -- predicate  fun g => ∀ args, denoteP (g Id args) = e args
      let pred ← withLocalDeclD `g gTy fun gv => do
        let lhs ← mkAppOptM ``denoteP #[Op, τ, mkAppN gv (#[idExpr] ++ args)]
        let eq ← mkEq lhs (e.beta args)
        mkLambdaFVars #[gv] (← mkForallFVars args eq)
      -- proof  fun args => rfl   (well-typed because denoteP (g Id args) ≡ e args)
      let dp ← mkAppOptM ``denoteP #[Op, τ, mkAppN g (#[idExpr] ++ args)]
      let prf ← mkLambdaFVars args (← mkEqRefl dp)
      mkAppOptM ``Subtype.mk #[gTy, pred, g, prf]

/-! ## A pretty-printer (instantiating `V := fun _ => String`) -/

/-- Pretty-print a pure term, threading a fresh-name counter. -/
def ppT : {α : Type} → Nat → Tm (fun _ => String) α → (String × Nat)
  | _, i, .var s => (s, i)
  | _, i, .lit n => (s!"{n}", i)
  | _, i, .lam f =>
    let v := s!"v{i}"
    let (body, n) := ppT (i + 1) (f v)
    (s!"λ{v} => {body}", n)
  | _, i, .app f a =>
    let (f, i) := ppT i f
    let (a, i) := ppT i a
    (s!"(({f})({a}))", i)
  | _, i, .letE e b =>
    let v := s!"v{i}"
    let i := i + 1
    let (e, i) := ppT i e
    let (b, i) := ppT i (b v)
    (s!"let {v} := {e}; {b}", i)

/-- Pretty-print a program.  Note the `op` case can render its input via `ppT` —
    that is only possible because the input is now a real term. -/
def ppProg {Op : Type → Type → Type} {α : Type}
    (name : {I R : Type} → Op I R → String) :
    Nat → Prog Op (fun _ => String) α → (String × Nat)
  | i, .ret x => ppT i x
  | i, .bind b f =>
    let v := s!"v{i}"
    let i := i + 1
    let (b, i) := ppProg name i b
    let (f, i) := ppProg name i (f v)
    (s!"let {v} ← {b}; {f}", i)
  | i, .op o inp f =>
    let (inpS, i) := ppT i inp
    let v := s!"v{i}"
    let i := i + 1
    let (contS, i) := ppProg name i (f v)
    (s!"let {v} ← {name o}({inpS}); {contS}", i)

/-! ## A concrete signature

The single source of truth — note `CircOp.assertNZ`'s input is a `Nat`, which in a
program will be supplied as a *term* (often a variable). -/

inductive CircOp : Type → Type → Type
  /-- Ask for a hint computed from a seed `Nat`; returns the `Nat`. -/
  | hint     : CircOp Nat Nat
  /-- Assert the input `Nat` is nonzero; returns `Unit`. -/
  | assertNZ : CircOp Nat Unit

/-- Operation names, for the pretty-printer. -/
def CircOp.name : {I R : Type} → CircOp I R → String
  | _, _, .hint     => "hint"
  | _, _, .assertNZ => "assertNZ"

/-- Runtime smart constructors, living in the ordinary `Free (Effect CircOp)`. -/
def hintF (seed : Nat) : Free (Effect CircOp) Nat :=
  Free.Impure ⟨CircOp.hint, seed⟩ Free.Pure
def assertNZ (x : Nat) : Free (Effect CircOp) Unit :=
  Free.Impure ⟨CircOp.assertNZ, x⟩ Free.Pure

/-! ## Examples / smoke tests -/

section Examples

variable {V : Type → Type} {α : Type}

/-- Pure fragment: `let f := id in f x`. -/
def pureExample : Tm V (α → α) :=
  .lam (fun x => .letE (.lam (fun y => .var y)) (fun f => .app (.var f) (.var x)))

example : denoteT (pureExample (V := Id) (α := Nat)) = (fun x => x) := rfl

#eval ppT 0 (pureExample (α := Nat))   -- "λv0 => let v1 := λv2 => v2; ((v1)(v0))"

/-- A real Lean `do`-block.  Crucially, `assertNZ n` feeds the *variable* `n`
    (bound by the preceding `hint`) into the effect's input position, and the
    function argument `k` becomes a literal.  The result threads `n` rather than
    computing on it, so the whole thing reflects into a `∀ V` program. -/
def hostExample (k : Nat) : Free (Effect CircOp) Nat := do
  let n ← hintF k
  let _ ← assertNZ n
  pure n


/-- Reflecting it yields a **closed** (`∀ V`) AST plus a `rfl`-backed soundness proof. -/
def reflectedExample := reflect% hostExample

#check (reflectedExample.1 : (V : Type → Type) → Nat → Prog CircOp V Nat)

/-- Soundness for every argument (denotation taken at `V := Id`). -/
example : ∀ k, denoteP (reflectedExample.1 Id k) = hostExample k := reflectedExample.2

/-- Closed case (`n = 0` arguments): `reflect%`'s program is literally a `Closed`. -/
example : denoteP ((reflect% (hostExample 7)).1 Id) = hostExample 7 :=
  (reflect% (hostExample 7)).2

-- Because the reflected program is polymorphic in `V`, we can now pretty-print it
-- (instantiating `V := fun _ => String`).  With `k := 99`:
--   "let v0 ← hint(99); let v1 ← assertNZ(v0); v0"
#eval ppProg CircOp.name 0 (reflectedExample.1 (fun _ => String) 99)

-- And it denotes back to an ordinary `Free (Effect CircOp)` computation:
#check (denoteP (reflectedExample.1 Id 99) : Free (Effect CircOp) Nat)

end Examples

end ZkFree
